name: master_build
on:
  push:
    branches:
      - master

jobs:
  UI_test_functional:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: |
          cd $GITHUB_WORKSPACE/_ref/docker-selenium
            docker-compose -f docker-compose-v3.yml up -d  --scale chrome=3
            echo 'sleep a while to let docker steady'
            sleep 30

            docker-compose -f docker-compose-v3.yml ps
          cd $GITHUB_WORKSPACE

      - name: prepare ubuntu
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv

      - run: |
          pipenv run pytest ./src
